# Generated by Django 4.1.7 on 2023-03-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_title_menuitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
    ]
